
dist: bionic

env:
    R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

install:
  - sudo apt update
  - sudo apt install -y flatpak python3 python3-pip
  - bash install-flatpak.sh
  - python3 -m pip install -r requirements.txt

script:
  - export R_VERSION=`flatpak run org.jamovi.jamovi --r-version`

  - mkdir -p libs
  - mkdir -p repo
  - python3 download.py --packages drat ggplot2 jsonlite
  - flatpak run --devel org.jamovi.jamovi -R CMD INSTALL --build *.tar.gz --library=libs
  - flatpak run --devel org.jamovi.jamovi -R -e "options(dratRepo='$APPVEYOR_BUILD_FOLDER/repo'); lapply(list.files(pattern='R_x86_64-pc-linux-gnu\\\\.tar\\\\.gz$'), drat::insertPackage)"
  - ls
  
