
dist: bionic

env:
    MRAN_SNAPSHOT: 2020-01-01
    R_LIBS_USER: libs

install:
  - sudo apt update
  - sudo apt install -y flatpak python3 python3-pip
  - bash install-flatpak.sh
  - python3 -m pip install -r requirements.txt

script:
  - echo done
  
