
image: Ubuntu

environment:
    CRAN_MIRROR: https://cran.microsoft.com/snapshot/2020-01-01
    R_LIBS_USER: libs

install:
  - sudo add-apt-repository ppa:alexlarsson/flatpak
  - sudo apt update
  - sudo apt install -y flatpak python3.7 python3-pip
  
  - bash install-flatpak.sh
  - python3 -m pip install -r requirements.txt

build_script:
  - export R_VERSION=`flatpak run org.jamovi.jamovi --r-version`
  - mkdir -p libs
  - mkdir -p repo
#   - mkdir -p downloads
#   - flatpak run --devel org.jamovi.jamovi -R -e "
#       install.packages(
#         repos='$CRAN_MIRROR',
#         keep_outputs=TRUE,
#         lib='installed',
#         destdir='downloads',
#         pkgs=readLines('packages.txt'))"
  - python3 download.py --packages drat ggplot2 jsonlite
  - flatpak run --devel org.jamovi.jamovi -R CMD INSTALL --build *.tar.gz --library=libs
  - flatpak run --devel org.jamovi.jamovi -R -e "options(dratRepo='$APPVEYOR_BUILD_FOLDER/repo'); lapply(list.files(pattern='R_x86_64-pc-linux-gnu\\\\.tar\\\\.gz$'), drat::insertPackage)"
  - ls

cache:
  - /home/appveyor/.local/share/flatpak/app/org.jamovi.jamovi -> install-flatpak.sh

artifacts:
  - name: repo
    path: 'repo/**/*'
