
image: Ubuntu2004

environment:
    APPVEYOR_CONSOLE_DISABLE_PTY: true
    SNAPSHOT: 2022-01-01
    CRAN_MIRROR: https://cran.microsoft.com/snapshot/2022-01-01
    R_LIBS_USER: libs
    SFTP_KEY:
        secure: XUbrKM80FYazJewKq8P+BYkG6xlsHrK05JndP6Ej3tU3sOH+jrgs2+ZRk3662guBgkHgxHwqbKbg3cP32tShsA3cRjMufoqqfkaiYWKVCD1CxiO9asKIT09pHFtFrXpACIAAO4m49xlMD9MynNQNrHD+UASj225JXdzbcjUz1zba03IrpGb6avwbKPDekZpFMY7ECId7NBIEoMbn/pB3sOy22eR8VJ4q1AKUVUOCywhat61mGmYhPCn2BVAPungQ0N0YZp+30onvhYS62ks6ImSzhNzI50uzm+mfugJ1tudnvzn2IsXZRvQCXJBJtOQ1F6wEsa91yxh6e6pczoMt8NY8d+E0UWrFRDR1jGvaP5jUn/pfy7vY9+bdUeMKMP2xktgg/rri93MWqpDRH29QsN3poOF+0tSAIId1oeui8V4D+CZDlqQAMJ4kswYoO22gL3MArxIayseLKEpMyEv1mfV3FP59/oJG/bgEFRtpkX+VJlacBThBpTNAtLS22xC54zRdpynkelq5rilka3ncMOpk3PjoLqDcic3eCkbnS5wpVd2BJ4xqNAEbWx70QbVHC8B/QfshhYtR58TYOxpxc+yp47hzdTQnny4rXQiY1gYeVmpFLdC/wfOXM0ccPXdTbK1SA6i5CJV8sQsoo6usAxPFHFgVtaI7gX34AZ+LK5V7uZIcKWJv5ZGghEDNBeiExr9ADKAzXFzLpQpgcU94cdBkUieK031zuRQtRX/gTz16ULDTYt/ymrK8Ap/KmW66J6+A40cUs49QvoZFZb0biV7MFDmxxKSF5MdxAbD2NNMlsK7T4SGxblD0f4UZ5+qtxw/l9xPsWt/bvcR0qT7hOY5G2Q8deY39pQm4SZC62Dh5F5ZbRTBksdZ5FtI6qkpOLrQnMOhoRwtXkrsJ/+OmKddRmDdLWilP98HZLWZ1G8Yu4NuDstQD+tJNJ4/bODRk6m4/+IU2M1S/K+Sq4FwT0OfBbFuTMCIYlZiBKm8hHs2/NNz6CYtULS0AnJISqATtVuO0T4avtsZlJTVI9Boe3dGNg9HCmHjIUZonS6UCFD/mmEWyWIraVE5NWm9BNQLRIGZZk59Lu5RQEbw1QD/l0GHrd2+FLHsOsnwNErDh/9dxj4lXN0RupE3sE9l+6sXXP7g/UeJJtmbGbDwvqbgCDIxzPD/np3MZxHsAkQQJfJHhcZpwRYGfyKoHUiIFe2gLf7G/D+ijsF7jH/m3XTJHDQCizoBhamL2Sfw1vkZ/r23m0f4Ta9ZsduztCUvBE8UDXOspsYn1k1gps4C4sXc572O/5RdNQki4LAZWHtoiNTKQfHdYEWQH1qw4kf3jxqy9pfp98LCDVYenrPsqWEHPRex4saq0xJoi0ruYqW4Qywcc1+om5ursXM8tieYlH4gC8LsKEUL86H12/YFUlhXcl2PzVtm26Y8Tg7MSaKUF/CkB07M5MUNgaWSxjZljX37hSuocspqLDEYk8c2030mJs3SOcbzQNidf4ISoLqWF3E2W8bl10woFdOI98qGOXNpv5KRO99+WBQB+99mE1PE/f/zBZ6P25iHOAacKLvCQlh1an5DKGaOiSjkzY/kmGhy39Y28Ngl8j/XE2enRDMik7L+3svQ8CFHrm8ZxRKhVXWOkcmh0Hv2J1IsVCB1H1wxjRxRLNB2l7l9FtqQvVQls4yTs448//xRTI4Hm+uLuTG36yl1bgGoNL38qnx+71D52PRAyh9LZPORu7S/XaDPUMieVjuv7HmhMzxzlm+BjQqSUUY00Ytm9kUtQMt6rxg3Yw8EtJBPAj1ykuOVmnInYV9D+iWWHp1rUtYy0cR0135Om1rMwQNd+tvcUdr2f5PzJsHcpGT4rQrSa+0e3rPImHArdmEOlsca8y0xVrXbDdDEVxljzACqHanXmpV7KD3XguzSZ+d/wpZwNY1epyroQkW527J9gdnT3CaKmTEnRmpS68OTa5N5ecgpqZYXMBMbc+OH90vwKBc7sNwkxivaAmHC6Ky9/8lADILofZf0HpvTl4w3iglFVEeN4f5IZOvxuiMgm3Kc8Q96eQxbHIsJH1yi9V28L87AWERFgtLxPZCHJ4PCuS7xPTSLitw42B1Vit0Txo0bKKWFZbYmznwdwzM+3HesNZLx0oadCMOOnmdB8M5OXCZUxgJX7EBdEF2QXzbxetEFg497WcldpdNANrNPyi/va2qjffEOhsRM905LbfKxTS7d3YKHIJQozXJiJaQ/yq3cwg8+WFVNceMAWrmPh0rtML1bsUeQt5wsWffzHTgLSt7s/9TQBfoFRqBp/JFYcskHB6z/NMpM0dniZtLPqa+AegtkEIkAKbabhAyqib7TDZ/ZxIhuEBa36nrXkz6+5jSFWediRKAqp60MngVTxi3DUyyn3dAAnj+dCTOUEDDNrOp7Rq3+IbwixVqga+3bkdFmOkQez8TwTcb6yC28y+3f0tj7TumieMlpbRE4SLz55ZIsLioNCCFyH2rqvDhQjvnwu7VubY0a9vPQM2g4GctXhCXPRw17lzLJtnCYpDR9sdTNCndiV2B1/0EyxK3H+kFu0dOIKMxvj0a8l2TAPi2ha5M3r5Y4CfAM4BIx309rJTs76oZcchqNH3Ee6PITPrjcpgpuldxZ7WLEzEuN0Nr6flsN+phhHEXwMbzCcjRZQQJ3cpYcHMq/tICSXstk4m6m057Phln2fvMSSQv/Pdp19fYHoDiYGXQRuAYuY5uARBpVIn7vfpA35dEbR5G3nw7tNJ3wn2C9JDOZs9dbtCDG/k1r3CxblNaFsz7F00VHYQoNvsL1kbxtnh0thOQN4dKlxnDzPMrAQsdyIUsECG7ZaHijuygzPzb342UsWjh28QWRziL6S+jsg713mWHmWwCHmS5WBxW/h6iNvPgMq95dfgIYXvIaJFNsYNNmyuAK716UIhQVhC03Nv40igsLOZK9MCLcYxvChU95VjUAG+WbOFFziJ+AdIA4Z6hI=
    SFTP_USER:
        secure: l4mG8sI6N3F1niJ6euSU3A==
    SFTP_KNOWNHOSTS:
        secure: J4PhvJkySks9v0kRrhCHJYaFZcEbNq1X1v0aDwrsACvDP7BK6MPUr37A7hjW2iuMgv9X2yYEcnm4u07E1X4fICr6mEH5xZhUuYsTf3jGYEPap3yk4VYz8mKPMemL/zmDNXigdgX/eswuvkibX7jcrgsZvmCFz1uWqW4OG3eS3JyjRJ46ZlUjtrmXVAUF8G74sBuG8WiIkW2G5p+DRWRuiTjHzNoO4P+1iYppN2ZrkyQs5qpy1CysW6D52z/n17TTSqyOiuRYAXlecvr4b8v4rKHZoyZmOEggopx74cRz+4rvy9xBh3rkYKy5vGl6PxSJrbA7V3+MnSs9+wuWE8dctjxv24S9CGl7n/gkLnQpuyVmDq2JuClEfeLlvdDH+PVXAtRG61x4xiP17yG9Ldoh2ghYNlBhfN6QcIm2h8wzMq2gANjjBbf0N8mz4D2VjkLvi+oYyz0ijney+XAWRDSRjyYUg+u0NDbcFWXP9QgIXaM=

install:
  - sudo apt update
  - sudo apt install -y flatpak python3 python3-pip rename curl
  
  - bash install-flatpak.sh
  - export APPVEYOR_SAVE_CACHE_ON_ERROR=true
  - python3 -m pip install -r requirements.txt

build_script:
  - export R_VERSION=`flatpak run org.jamovi.jamovi --r-version`
  - mkdir -p $R_LIBS_USER
  - python3 download.py --packages drat `sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/ /g' packages.txt`
  - flatpak run --devel org.jamovi.jamovi -R CMD INSTALL --build *.tar.gz --library=$R_LIBS_USER
  - rename 's/^(.*)_R_x86_64-pc-linux-gnu\.tar\.gz$/$1.tar.gz.tmp/' *_R_x86_64-pc-linux-gnu.tar.gz
  - rm -rf *.tar.gz
  - rename 's/^(.*)\.tmp/$1/' *.tar.gz.tmp
  - mkdir -p $R_VERSION
  - mkdir -p $R_VERSION/$SNAPSHOT
  - flatpak run --devel org.jamovi.jamovi -R -e "options(dratRepo='$APPVEYOR_BUILD_FOLDER/$R_VERSION/$SNAPSHOT'); lapply(list.files(pattern='\\\\.tar\\\\.gz$'), drat::insertPackage); invisible(NULL)"

after_build:
  - mkdir -p ~/.ssh
  - chmod 0700 ~/.ssh
  - echo "${SFTP_KEY}" | base64 --decode >~/.ssh/id_rsa
  - chmod 0600 ~/.ssh/id_rsa
  - echo "${SFTP_KNOWNHOSTS}" | base64 --decode >>~/.ssh/known_hosts
  - scp -r -o IdentityFile=~/.ssh/id_rsa "$APPVEYOR_BUILD_FOLDER/$R_VERSION" ${SFTP_USER}@jamovi.org:/home/${SFTP_USER}/jamovi.org/downloads/repo

cache:
  - /home/appveyor/.local/share/flatpak/app/org.jamovi.jamovi -> install-flatpak.sh
